# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='devices',
            new_name='tank',
        ),
    ]
