# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20171003_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('timestamp',), 'verbose_name_plural': 'Status'},
        ),
    ]
