# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20171003_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devicelink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slave_device', to='devices.DeviceLink'),
        ),
    ]
